apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lms-services
  labels:
    app: lab-ms-ui
  name: lab-ms-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-ms-ui
  template:
    metadata:
      labels:
        app: lab-ms-ui
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: lab-ms-ui
          image: registry.gitlab.com/lab-ms/lab-ms-ui:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: lms-frontend
                  key: NODE_ENV
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: lms-services
  name: lab-ms-ui
  labels:
    app: lab-ms-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: lab-ms-ui
