FROM node:16.19.0-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app
COPY packages ./packages

COPY package.json turbo.json ./
COPY apps/lab-next-app/package.json ./apps/lab-next-app/


RUN cat ./apps/lab-next-app/package.json

RUN yarn cache clean && \
    yarn



# Rebuild the source code only when needed
FROM base AS builder
RUN apk add --no-cache libc6-compat

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/yarn.lock ./

COPY . .
COPY --from=deps /app/yarn.lock ./

RUN yarn global add turbo
RUN turbo --version
RUN ls -la

CMD ["yarn", "test:docker"]
